import { Inter } from "next/font/google";
import "./globals.css";
import { getAuth } from "@/features/auth/queries/get-auth";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Provider } from "react-redux"; // Import Provider
import store from "@/redux/store"; // Ensure this path is correct
import { StoreProvider } from "@/redux/storeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const auth = await getAuth();
  const user = auth?.user || null;

  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <NavBar user={user} />
          <hr />
          <main className="p-4">{children}</main>
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}
